### ISSUE TITLE
Fullscreen menu option throws error on main process while window closed

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-wallet#637]
Using 4.1.0 mac os

Close the window (either cmd-w, or click on the red pill on the window.

Issue 1: there is no way I could find to re-open the window (workaround: quit and relaunch)
Issue 2: while the window is closed, chose "View > Toggle Full Screen" and you get an alert with:

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Object has been destroyed
    at click (/Applications/Stacks Wallet 4.1.0.app/Contents/Resources/app.asar/main.prod.js:275:58)
    at MenuItem.click (electron/js2c/browser_init.js:1549:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1810:13)
```

**Comment by kyranjamie** [comment]
Great find @psq, thanks

I was only able to replicate this with <kbd>⌘ CMD</kbd>+<kbd>W</kbd>, not the red close btn.

**Comment by kyranjamie** [comment]
MacOS convention is to not quit an application on close. This is adhered to here, but fullscreen logic isn't handled when it is closed. 

Github's Electron app simply hides the app:
https://github.com/desktop/desktop/blob/6f950eca2734efedce5f9013292430f93f939566/app/src/main-process/app-window.ts#L72-L82

**Comment by psq** [comment]
what I was looking for was for a way to reopen the window.  Most apps I use that adhere to that convention have a way to reopen the main window, e.g. Mail (short of quitting and relaunching), but obviously not critical.  The alert does look out of place, but this may require a fix in Electron itself...
