### ISSUE TITLE
build fails on fresh install (branch: feature/software-wallet)

### ISSUE THREAD

**Issue by dominictarr** [blockstack/stacks-wallet#86]
**Describe the bug**
yarn build/install etc fails with an error

**To Reproduce**
clone the repo, rm -rf node_modules, yarn install

**Expected behavior**
it works, and then app can be started

**Additional context**

seems like something to do with babel?
```
[0] /home/dominic/c/stacks-wallet/node_modules/webpack-cli/bin/cli.js:244
[0]                             throw err;
[0]                             ^
[0] 
[0] TypeError: t(...).isPlaceholder is not a function
[0]     at placeholderVisitorHandler (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/template/lib/parse.js:81:11)
[0]     at traverseSimpleImpl (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/types/lib/traverse/traverse.js:27:14)
[0]     at Object.traverse (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/types/lib/traverse/traverse.js:21:3)
[0]     at parseAndBuildMetadata (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/template/lib/parse.js:65:7)
[0]     at buildLiteralData (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/template/lib/literal.js:53:35)
[0]     at literalTemplate (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/template/lib/literal.js:20:7)
[0]     at Function.ast (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/template/lib/builder.js:52:42)
[0]     at Object.ast (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/lib/helpers.js:26:42)
[0]     at fn (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/lib/index.js:245:30)
[0]     at loadHelper (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/lib/index.js:248:40)
[0]     at Object.minVersion (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/lib/index.js:275:10)
[0]     at File.availableHelper (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transformation/file/file.js:180:30)
[0]     at file.set.name (/home/dominic/c/stacks-wallet/node_modules/@babel/plugin-transform-runtime/lib/index.js:155:45)
[0]     at File.addHelper (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transformation/file/file.js:197:19)
[0]     at wrapInterop (/home/dominic/c/stacks-wallet/node_modules/@babel/helper-module-transforms/lib/index.js:165:45)
[0]     at PluginPass.exit (/home/dominic/c/stacks-wallet/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:174:70)
[0]     at newFn (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:193:21)
[0]     at NodePath._call (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
[0]     at NodePath.call (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
[0]     at NodePath.visit (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:8)
[0]     at TraversalContext.visitQueue (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:118:16)
[0]     at TraversalContext.visitSingle (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:90:19)
[0]     at TraversalContext.visit (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:146:19)
[0]     at Function.traverse.node (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:94:17)
[0]     at traverse (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:76:12)
[0]     at transformFile (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transformation/index.js:88:29)
[0]     at runSync (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transformation/index.js:45:3)
[0]     at transformSync (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transform.js:43:38)
[0]     at Object.transform (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transform.js:22:38)
[0]     at compile (/home/dominic/c/stacks-wallet/node_modules/@babel/register/lib/node.js:73:20)
[1] /home/dominic/c/stacks-wallet/node_modules/webpack-cli/bin/cli.js:244
[1]                             throw err;
[1]                             ^
[1] 
[1] TypeError: t(...).isPlaceholder is not a function
[1]     at placeholderVisitorHandler (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/template/lib/parse.js:81:11)
[1]     at traverseSimpleImpl (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/types/lib/traverse/traverse.js:27:14)
[1]     at Object.traverse (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/types/lib/traverse/traverse.js:21:3)
[1]     at parseAndBuildMetadata (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/template/lib/parse.js:65:7)
[1]     at buildLiteralData (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/template/lib/literal.js:53:35)
[1]     at literalTemplate (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/template/lib/literal.js:20:7)
[1]     at Function.ast (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/node_modules/@babel/template/lib/builder.js:52:42)
[1]     at Object.ast (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/lib/helpers.js:26:42)
[1]     at fn (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/lib/index.js:245:30)
[1]     at loadHelper (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/lib/index.js:248:40)
[1]     at Object.minVersion (/home/dominic/c/stacks-wallet/node_modules/@babel/helpers/lib/index.js:275:10)
[1]     at File.availableHelper (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transformation/file/file.js:180:30)
[1]     at file.set.name (/home/dominic/c/stacks-wallet/node_modules/@babel/plugin-transform-runtime/lib/index.js:155:45)
[1]     at File.addHelper (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transformation/file/file.js:197:19)
[1]     at wrapInterop (/home/dominic/c/stacks-wallet/node_modules/@babel/helper-module-transforms/lib/index.js:165:45)
[1]     at PluginPass.exit (/home/dominic/c/stacks-wallet/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:174:70)
[1]     at newFn (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:193:21)
[1]     at NodePath._call (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
[1]     at NodePath.call (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
[1]     at NodePath.visit (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:8)
[1]     at TraversalContext.visitQueue (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:118:16)
[1]     at TraversalContext.visitSingle (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:90:19)
[1]     at TraversalContext.visit (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:146:19)
[1]     at Function.traverse.node (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:94:17)
[1]     at traverse (/home/dominic/c/stacks-wallet/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:76:12)
[1]     at transformFile (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transformation/index.js:88:29)
[1]     at runSync (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transformation/index.js:45:3)
[1]     at transformSync (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transform.js:43:38)
[1]     at Object.transform (/home/dominic/c/stacks-wallet/node_modules/@babel/core/lib/transform.js:22:38)
[1]     at compile (/home/dominic/c/stacks-wallet/node_modules/@babel/register/lib/node.js:73:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[0] yarn build-main exited with code 1
[1] yarn build-renderer exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by dominictarr** [comment]
oh btw, yarn says it the lock file needs an update, if that helps

**Comment by friedger** [comment]
Using yarn 1.16 fixed this error for me.

**Comment by markmhx** [comment]
I'm closing this out given that the yarn update fixes the error.
